### ISSUE TITLE
Feedback, Ideas and Enhancements

### ISSUE THREAD

**Issue by hofmannsven** [hofmannsven/cleverreach-extension#1]
Feel free to give feedback and/or share your ideas for plugin improvements and enhancements :)

Please check the [roadmap](https://github.com/hofmannsven/cleverreach-extension/projects/1) for further information.

**Comment by konus1** [comment]
I would like to offer a user the possibility to change his subscription data by himself in a webform:
example: change frequency of newsletter from daily to weekly

**Comment by hofmannsven** [comment]
I've published a short tutorial on how to set up a [custom form](https://github.com/hofmannsven/cleverreach-extension/wiki/Custom-forms) including a simple dropdown (using the HTML `<select>` tag) within the [Wiki](https://github.com/hofmannsven/cleverreach-extension/wiki). 

@konus1: I've tried to keep the tutorial as general as possible but I think you'll get the idea. Let me know if you need further help with this.

**Comment by konus1** [comment]
Thank you very much!

Unfortunately further investigation of cleverreach showed me, that is is currently impossible to automatically send an email only if there is a new article in my rss-feed. Since I do not post every day and often not even every week, this would result in a empty newsletter email.  
I was told that this feature may be available in a later version of cleverreach. Until then I can not use this service.

**Comment by vic-snippets** [comment]
Hi @hofmannsven ,

Great plugin. One thing... the plugin is not catching "Email Blocked" errors. I put *@gmail.com in the blacklist for a list (not global). If I use your plugin any @gmail.com makes the list. The html form that CleverReach gives works fine as an @gmail.com throws up a "Blocked Email" error message.

Anyway to make this work?

Thanks,
Victor

**Comment by zitrusblau** [comment]
Hey,
just found your plugin which looks very promising.
I was looking for a solution to use the cleverreach signup with a custom form/cf7 form but need a way to dynamically set the list_id (depending on the current locale).

so, since this is scheduled for the 0.3.0 release i was wondering if you found the time to work on this recently?
I understand if you started to do a rewrite for the REST API instead though...

**Comment by hofmannsven** [comment]
Thank you for your feedback, @zitrusblau.
I don't quite get what you mean, but you can [append the locale to the ajax request](https://github.com/hofmannsven/cleverreach-extension/wiki/Custom-ajax-requests).
As a workaround, you can create multiple forms with different list IDs for each of them.

**Comment by zitrusblau** [comment]
Hey Sven,
thanks for your reply.

After some research in how cleverreach organizes it's data (groups aka lists and forms) and the signup form integration happens to be on a WP multisite, this task was rather trivial since the plugin settings can be adjusted for every site/blog instance separately and set a different form id there (setting the locale via a hidden input form field).

so everything is working for us now.

looking forward to the planned native cf7 integration, though.

**Comment by hofmannsven** [comment]
I've moved this issue to the projects tab on GitHub: [Roadmap](https://github.com/hofmannsven/cleverreach-extension/projects/1).
