### ISSUE TITLE
No SSL support?

### ISSUE THREAD

**Issue by reqwire** [hofmannsven/cleverreach-extension#14]
So while using the shortcode (instead of copying the embed code from the CleverReach website)  I've hit a snag with a mixed content error on my https Wordpress page. The problem is that the shortcode itself does not support an SSL encryption option. 

Until this is fixed sadly my webpage will remain insecure.

**Comment by hofmannsven** [comment]
Thank you very much for your feedback.
I think this has already been reported and fixed in one of the latest commits.

So maybe you can upgrade to the latest version (see [master branch](https://github.com/hofmannsven/cleverreach-extension/tree/master)) of the plugin:
» https://github.com/hofmannsven/cleverreach-extension/archive/master.zip
